- name: check out Frontend code
  git: 
    repo=https://github.com/andrewhilts/transparency-frontend.git
    version=master
    dest={{webRoot}}{{transLocalPath}}

- name: use stable NVM
  shell: source ~/.profile && nvm use stable
  args:
     executable: /bin/bash

- name: install grunt-cli & bower
  shell: source ~/.profile && npm install -g grunt-cli bower
  args:
     executable: /bin/bash

- name: install node plugins
  shell: source ~/.profile && npm install
  args:
    executable: /bin/bash
    chdir: "{{webRoot}}{{transLocalPath}}"

- name: install bower plugins
  shell: source ~/.profile && bower install
  args:
    executable: /bin/bash
    chdir: "{{webRoot}}{{transLocalPath}}"

- name: Add frontend Config
  template: src="config.js.j2" dest="{{webRoot}}{{transLocalPath}}/app/scripts/modules/config/config.js"
  notify: restart nginx